const PERMISSION_CODES = {
  ONE_SHIFT_THREE_CHECKS_ENTRY: "PINGAN_ONE_SHIFT_THREE_CHECKS_ENTRY",
  ONE_SHIFT_THREE_CHECKS_VIEW: "PINGAN_ONE_SHIFT_THREE_CHECKS_VIEW",
  ONE_SHIFT_THREE_CHECKS_CREATE: "PINGAN_ONE_SHIFT_THREE_CHECKS_CREATE",
  ONE_SHIFT_THREE_CHECKS_UPDATE: "PINGAN_ONE_SHIFT_THREE_CHECKS_UPDATE",
  ONE_SHIFT_THREE_CHECKS_SUBMIT: "PINGAN_ONE_SHIFT_THREE_CHECKS_SUBMIT",
  ONE_SHIFT_THREE_CHECKS_DELETE: "PINGAN_ONE_SHIFT_THREE_CHECKS_DELETE",
  ONE_SHIFT_THREE_CHECKS_VOID: "PINGAN_ONE_SHIFT_THREE_CHECKS_VOID",
  ONE_SHIFT_THREE_CHECKS_REMIND: "PINGAN_ONE_SHIFT_THREE_CHECKS_REMIND",
  ONE_SHIFT_THREE_CHECKS_RECTIFICATION_ORDER_CREATE: "PINGAN_ONE_SHIFT_THREE_CHECKS_RECTIFICATION_ORDER_CREATE",
  PRE_SHIFT_MEETING_ENTRY: "PINGAN_PRE_SHIFT_MEETING_ENTRY",
  PRE_SHIFT_MEETING_VIEW: "PINGAN_PRE_SHIFT_MEETING_VIEW",
  PRE_SHIFT_MEETING_CREATE: "PINGAN_PRE_SHIFT_MEETING_CREATE",
  PRE_SHIFT_MEETING_UPDATE: "PINGAN_PRE_SHIFT_MEETING_UPDATE",
  PRE_SHIFT_MEETING_SUBMIT: "PINGAN_PRE_SHIFT_MEETING_SUBMIT",
  PRE_SHIFT_MEETING_DELETE: "PINGAN_PRE_SHIFT_MEETING_DELETE",
  PRE_SHIFT_MEETING_VOID: "PINGAN_PRE_SHIFT_MEETING_VOID",
  PRE_SHIFT_MEETING_REMIND: "PINGAN_PRE_SHIFT_MEETING_REMIND",
  TEAM_DISPATCH_ENTRY: "PINGAN_TEAM_DISPATCH_ENTRY",
  TEAM_DISPATCH_VIEW: "PINGAN_TEAM_DISPATCH_VIEW",
  THREE_CHECK_ENTRY: "PINGAN_THREE_CHECK_ENTRY",
  THREE_CHECK_VIEW: "PINGAN_THREE_CHECK_VIEW",
  THREE_CHECK_EXECUTE: "PINGAN_THREE_CHECK_EXECUTE",
  TEAM_DISPATCH_MANAGE: "PINGAN_TEAM_DISPATCH_MANAGE",
  THREE_CHECK_WITHDRAW: "PINGAN_THREE_CHECK_WITHDRAW",
  THREE_CHECK_REMIND: "PINGAN_THREE_CHECK_REMIND",
  KEY_SITES_ENTRY: "PINGAN_KEY_SITES_ENTRY",
  KEY_SITES_VIEW: "PINGAN_KEY_SITES_VIEW",
  SPECIAL_WORK_ENTRY: "PINGAN_SPECIAL_WORK_ENTRY",
  SPECIAL_WORK_VIEW: "PINGAN_SPECIAL_WORK_VIEW",
  SPECIAL_WORK_APPLY: "PINGAN_SPECIAL_WORK_APPLY",
  SPECIAL_WORK_APPROVE: "PINGAN_SPECIAL_WORK_APPROVE",
  SPECIAL_WORK_REVIEW: "PINGAN_SPECIAL_WORK_REVIEW",
  HAZARD_ENTRY: "PINGAN_HAZARD_ENTRY",
  HAZARD_VIEW: "PINGAN_HAZARD_VIEW",
  HAZARD_QUICK_SHOT_ENTRY: "PINGAN_HAZARD_QUICK_SHOT_ENTRY",
  HAZARD_QUICK_SHOT_VIEW: "PINGAN_HAZARD_QUICK_SHOT_VIEW",
  HAZARD_QUICK_SHOT_REPORT: "PINGAN_HAZARD_QUICK_SHOT_REPORT",
  HAZARD_QUICK_SHOT_REVIEW: "PINGAN_HAZARD_QUICK_SHOT_REVIEW",
  HAZARD_SAFETY_CHECK_ENTRY: "PINGAN_HAZARD_SAFETY_CHECK_ENTRY",
  HAZARD_SAFETY_CHECK_VIEW: "PINGAN_HAZARD_SAFETY_CHECK_VIEW",
  HAZARD_SAFETY_CHECK_CREATE: "PINGAN_HAZARD_SAFETY_CHECK_CREATE",
  HAZARD_RECTIFICATION_ENTRY: "PINGAN_HAZARD_RECTIFICATION_ENTRY",
  HAZARD_RECTIFICATION_VIEW: "PINGAN_HAZARD_RECTIFICATION_VIEW",
  HAZARD_RECTIFICATION_CREATE: "PINGAN_HAZARD_RECTIFICATION_CREATE",
  HAZARD_RECTIFICATION_RECTIFY: "PINGAN_HAZARD_RECTIFICATION_RECTIFY",
  HAZARD_RECTIFICATION_ACCEPT: "PINGAN_HAZARD_RECTIFICATION_ACCEPT",
  HAZARD_RECTIFICATION_VOID: "PINGAN_HAZARD_RECTIFICATION_VOID",
  HAZARD_REPORT: "PINGAN_HAZARD_REPORT",
  HAZARD_ACCEPT: "PINGAN_HAZARD_ACCEPT",
  HAZARD_RECTIFICATION: "PINGAN_HAZARD_RECTIFICATION",
  HAZARD_CLOSE: "PINGAN_HAZARD_CLOSE",
  TRAINING_ENTRY: "PINGAN_TRAINING_ENTRY",
  TRAINING_VIEW: "PINGAN_TRAINING_VIEW",
  TRAINING_STUDY_EXAM: "PINGAN_TRAINING_STUDY_EXAM",
  SAFETY_LEARNING_ENTRY: "PINGAN_TRAINING_SAFETY_LEARNING_ENTRY",
  SAFETY_LEARNING_VIEW: "PINGAN_TRAINING_SAFETY_LEARNING_VIEW",
  EXAM_TASKS_ENTRY: "PINGAN_TRAINING_EXAM_TASKS_ENTRY",
  EXAM_TASKS_VIEW: "PINGAN_TRAINING_EXAM_TASKS_VIEW",
  POINTS_ENTRY: "PINGAN_POINTS_ENTRY",
  POINTS_VIEW: "PINGAN_POINTS_VIEW",
  POINTS_RANKING_ENTRY: "PINGAN_POINTS_RANKING_ENTRY",
  POINTS_RANKING_VIEW: "PINGAN_POINTS_RANKING_VIEW"
}

const HAZARD_PERMISSION_GROUPS = {
  quickShot: [
    PERMISSION_CODES.HAZARD_ENTRY,
    PERMISSION_CODES.HAZARD_QUICK_SHOT_ENTRY,
    PERMISSION_CODES.HAZARD_QUICK_SHOT_VIEW
  ],
  quickShotReport: [
    PERMISSION_CODES.HAZARD_QUICK_SHOT_REPORT,
    PERMISSION_CODES.HAZARD_REPORT
  ],
  quickShotReview: [
    PERMISSION_CODES.HAZARD_QUICK_SHOT_REVIEW,
    PERMISSION_CODES.HAZARD_ACCEPT
  ],
  safetyCheck: [
    PERMISSION_CODES.HAZARD_ENTRY,
    PERMISSION_CODES.HAZARD_SAFETY_CHECK_ENTRY,
    PERMISSION_CODES.HAZARD_SAFETY_CHECK_VIEW
  ],
  safetyCheckCreate: [
    PERMISSION_CODES.HAZARD_SAFETY_CHECK_CREATE
  ],
  rectification: [
    PERMISSION_CODES.HAZARD_ENTRY,
    PERMISSION_CODES.HAZARD_VIEW,
    PERMISSION_CODES.HAZARD_RECTIFICATION_ENTRY,
    PERMISSION_CODES.HAZARD_RECTIFICATION_VIEW
  ],
  rectificationCreate: [
    PERMISSION_CODES.HAZARD_RECTIFICATION_CREATE,
    PERMISSION_CODES.HAZARD_REPORT
  ],
  rectificationRectify: [
    PERMISSION_CODES.HAZARD_RECTIFICATION_RECTIFY,
    PERMISSION_CODES.HAZARD_RECTIFICATION
  ],
  rectificationAccept: [
    PERMISSION_CODES.HAZARD_RECTIFICATION_ACCEPT,
    PERMISSION_CODES.HAZARD_ACCEPT
  ],
  rectificationVoid: [
    PERMISSION_CODES.HAZARD_RECTIFICATION_VOID,
    PERMISSION_CODES.HAZARD_CLOSE
  ]
}

const MODULE_PERMISSION_CODES = {
  dispatch: [
    PERMISSION_CODES.TEAM_DISPATCH_ENTRY,
    PERMISSION_CODES.TEAM_DISPATCH_VIEW
  ],
  meeting: [
    PERMISSION_CODES.PRE_SHIFT_MEETING_ENTRY,
    PERMISSION_CODES.PRE_SHIFT_MEETING_VIEW
  ],
  "before-check": [
    PERMISSION_CODES.ONE_SHIFT_THREE_CHECKS_ENTRY,
    PERMISSION_CODES.ONE_SHIFT_THREE_CHECKS_VIEW
  ],
  "during-check": [
    PERMISSION_CODES.ONE_SHIFT_THREE_CHECKS_ENTRY,
    PERMISSION_CODES.ONE_SHIFT_THREE_CHECKS_VIEW
  ],
  "after-check": [
    PERMISSION_CODES.ONE_SHIFT_THREE_CHECKS_ENTRY,
    PERMISSION_CODES.ONE_SHIFT_THREE_CHECKS_VIEW
  ],
  "key-place": [
    PERMISSION_CODES.KEY_SITES_ENTRY,
    PERMISSION_CODES.KEY_SITES_VIEW
  ],
  "special-work": [
    PERMISSION_CODES.SPECIAL_WORK_ENTRY,
    PERMISSION_CODES.SPECIAL_WORK_VIEW
  ],
  hazard: HAZARD_PERMISSION_GROUPS.rectification,
  snapshot: HAZARD_PERMISSION_GROUPS.quickShot,
  "safety-check": HAZARD_PERMISSION_GROUPS.safetyCheck,
  learning: [
    PERMISSION_CODES.SAFETY_LEARNING_ENTRY,
    PERMISSION_CODES.SAFETY_LEARNING_VIEW
  ],
  exam: [
    PERMISSION_CODES.EXAM_TASKS_ENTRY,
    PERMISSION_CODES.EXAM_TASKS_VIEW
  ],
  "point-flow": [
    PERMISSION_CODES.POINTS_ENTRY,
    PERMISSION_CODES.POINTS_VIEW
  ],
  "point-rank": [
    PERMISSION_CODES.POINTS_RANKING_ENTRY,
    PERMISSION_CODES.POINTS_RANKING_VIEW
  ]
}

const MODULE_LEGACY_PERMISSION_CODES = {
  dispatch: [PERMISSION_CODES.TEAM_DISPATCH_MANAGE],
  "dispatch-records": [PERMISSION_CODES.TEAM_DISPATCH_MANAGE],
  meeting: [PERMISSION_CODES.THREE_CHECK_VIEW],
  "before-check": [PERMISSION_CODES.THREE_CHECK_VIEW],
  "during-check": [PERMISSION_CODES.THREE_CHECK_VIEW],
  "after-check": [PERMISSION_CODES.THREE_CHECK_VIEW],
  learning: [PERMISSION_CODES.TRAINING_ENTRY, PERMISSION_CODES.TRAINING_VIEW],
  exam: [
    PERMISSION_CODES.TRAINING_ENTRY,
    PERMISSION_CODES.TRAINING_VIEW,
    PERMISSION_CODES.TRAINING_STUDY_EXAM
  ],
  "point-rank": [PERMISSION_CODES.POINTS_ENTRY, PERMISSION_CODES.POINTS_VIEW]
}

const THREE_CHECK_ACTION_PERMISSION_CODES = {
  CREATE: [PERMISSION_CODES.ONE_SHIFT_THREE_CHECKS_CREATE, PERMISSION_CODES.THREE_CHECK_EXECUTE],
  UPDATE: [PERMISSION_CODES.ONE_SHIFT_THREE_CHECKS_UPDATE, PERMISSION_CODES.THREE_CHECK_EXECUTE],
  SUBMIT: [PERMISSION_CODES.ONE_SHIFT_THREE_CHECKS_SUBMIT, PERMISSION_CODES.THREE_CHECK_EXECUTE],
  DELETE: [PERMISSION_CODES.ONE_SHIFT_THREE_CHECKS_DELETE],
  VOID: [PERMISSION_CODES.ONE_SHIFT_THREE_CHECKS_VOID, PERMISSION_CODES.THREE_CHECK_WITHDRAW],
  REMIND: [PERMISSION_CODES.ONE_SHIFT_THREE_CHECKS_REMIND, PERMISSION_CODES.THREE_CHECK_REMIND],
  RECTIFICATION_ORDER_CREATE: [PERMISSION_CODES.ONE_SHIFT_THREE_CHECKS_RECTIFICATION_ORDER_CREATE]
}

const PRE_SHIFT_MEETING_ACTION_PERMISSION_CODES = {
  CREATE: [PERMISSION_CODES.PRE_SHIFT_MEETING_CREATE],
  UPDATE: [PERMISSION_CODES.PRE_SHIFT_MEETING_UPDATE],
  SUBMIT: [PERMISSION_CODES.PRE_SHIFT_MEETING_SUBMIT],
  DELETE: [PERMISSION_CODES.PRE_SHIFT_MEETING_DELETE],
  VOID: [PERMISSION_CODES.PRE_SHIFT_MEETING_VOID],
  REMIND: [PERMISSION_CODES.PRE_SHIFT_MEETING_REMIND]
}

module.exports = {
  PERMISSION_CODES,
  HAZARD_PERMISSION_GROUPS,
  MODULE_PERMISSION_CODES,
  MODULE_LEGACY_PERMISSION_CODES,
  THREE_CHECK_ACTION_PERMISSION_CODES,
  PRE_SHIFT_MEETING_ACTION_PERMISSION_CODES
}
