package com.pingan.banzu.dto;

import java.util.List;

public record HazardRectificationOrderDetailResponse(
    String id,
    String orderNo,
    String sourceType,
    String sourceModuleKey,
    String sourceRecordId,
    String sourceRecordNo,
    String rootDispatchRecordId,
    Long companyId,
    String company,
    Long departmentId,
    String department,
    Long teamId,
    String team,
    String businessDate,
    int hazardCount,
    String status,
    String statusLabel,
    Long rectificationDepartmentId,
    Long rectificationResponsibleUserId,
    String rectificationResponsibleUserName,
    String rectificationRequirement,
    String rectificationDeadline,
    Long issuedBy,
    String issuedAt,
    Long rectifiedBy,
    String rectifiedAt,
    String rectificationDescription,
    String rectificationAfterPhoto,
    Long acceptanceUserId,
    String acceptanceUserName,
    Long acceptanceDepartmentId,
    String acceptanceAt,
    String acceptanceResult,
    String acceptanceRemark,
    String closedAt,
    int version,
    List<HazardRectificationOrderItemResponse> items,
    List<HazardRectificationFlowLogResponse> flowLogs) {}
